repos:
  - repo: local
    hooks:
      - id: pants-lint
        name: pants lint
        always_run: false
        description: runs pants --no-dynamic-ui lint on python files
        entry: "pants fix lint ::"
        language: system
